version: '2.0'
services:
  web:
    restart: always
    build:
      context: .
      dockerfile: ./web/Dockerfile
    ports:
     - "5000:5000"
    volumes:
      - ./code/p1:/app
    command: python /app/app.py
